---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "13:00"
    open-pull-requests-limit: 15
    assignees:
      - lopopolo
    labels:
      - A-deps
